name: Pull Request Action
on:
  push:
    branches:
      - feature/*
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Auto create pull request when someone push
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: upadte new change on ${{ github.ref }}
          title: New update adjustment by ${{ github.actor }}
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          body: |
            Update new changes ðŸ’¬:
            - Update new change on ${{ github.ref }}
          # branch: ${{ github.ref_name }}
          base: main
          reviewers: ThanhNha
          # delete-branch: true

